name: 'Hello World JavaScript Action'
description: 'Greet someone and log the time'

inputs:
  quem-cumprimentar:
    description: Quem cumprimentar
    required: true
    default: Mundo

outputs:
  tempo:
    description: O momento em que te cumprimentamos

branding:
  icon: 'activity'
  color: 'green'

runs:
  using: node20
  main: dist/index.js
